# Generated by Django 4.0.6 on 2022-07-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
    ]
