# Generated by Django 4.0.4 on 2022-07-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='print_exception',
            new_name='price',
        ),
    ]
